"""add category_id to transactions

Revision ID: b1122ba5e7ee
Revises: 3b8ad1f13954
Create Date: 2026-03-11 12:47:36.253787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1122ba5e7ee'
down_revision: Union[str, Sequence[str], None] = '3b8ad1f13954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
